CMDB/Controllers/ImportCIController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using CMDB.DAL;
using CMDB.Models;
using CMDB.ViewModels;
using CMDB.SystemClass;
using TWCAlib;
using LinqToExcel;

namespace CMDB.Controllers
{
    public class ImportCIController : Controller
    {
        CMDBContext context = new CMDBContext();
        SystemConfig Configer = new SystemConfig();
        ShareFunc SF = new ShareFunc();
        String log_Info = "Info";
        String log_Err = "Err";

        // GET: ImportCI
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(string ImportType, HttpPostedFileBase file)
        {
            string nowUser = Session["UserID"].ToString();
            int nowRole = Convert.ToInt32(Session["UserRole"]);
            int nowFunction = 15;

            //Log記錄用
            SystemLogs SL = new SystemLogs();
            SL.Account = nowUser;
            SL.Controller = "ImportCIController";
            SL.Action = "Upload";
            SL.StartTime = DateTime.Now;

            string MailServer = Configer.MailServer;
            int MailServerPort = Configer.MailServerPort;
            string MailSender = Configer.MailSender;
            List<string> MailReceiver = Configer.MailReceiver;

            JObject jo = new JObject();
            string result = string.Empty;

            SF.logandshowInfo("上傳檔案開始@" + SL.StartTime.ToString(Configer.SystemDateTimeFormat), log_Info);

            if (file == null)
            {
                SL.EndTime = DateTime.Now;
                SF.logandshowInfo("上傳檔案結束@" + SL.EndTime.ToString(Configer.SystemDateTimeFormat), log_Info);
                SF.logandshowInfo("上傳檔案失敗，錯誤訊息[無上傳檔案]", log_Info);
                SL.TotalCount = 1;
                SL.SuccessCount = 0;
                SL.FailCount = 1;
                SL.Result = false;
                SL.Msg = "上傳檔案失敗，錯誤訊息[無上傳檔案]";
                SF.log2DB(SL, MailServer, MailServerPort, MailSender, MailReceiver);

                jo.Add("Result", false);
                jo.Add("Msg", "錯誤訊息[無上傳檔案]");
                result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }
            if (file.ContentLength <= 0)
            {
                SL.EndTime = DateTime.Now;
                SF.logandshowInfo("上傳檔案結束@" + SL.EndTime.ToString(Configer.SystemDateTimeFormat), log_Info);
                SF.logandshowInfo("上傳檔案失敗，錯誤訊息[檔案大小為0]", log_Info);
                SL.TotalCount = 1;
                SL.SuccessCount = 0;
                SL.FailCount = 1;
                SL.Result = false;
                SL.Msg = "上傳檔案失敗，錯誤訊息[檔案大小為0]";
                SF.log2DB(SL, MailServer, MailServerPort, MailSender, MailReceiver);

                jo.Add("Result", false);
                jo.Add("Msg", "錯誤訊息[檔案大小為0]");

                result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }

            string fileExtName = Path.GetExtension(file.FileName).ToLower();
            SF.logandshowInfo("上傳檔案名稱:" + file.FileName, log_Info);
            SF.logandshowInfo("上傳檔案副檔名:" + fileExtName, log_Info);

            if (!fileExtName.Equals(".xls", StringComparison.OrdinalIgnoreCase)
                &&
                !fileExtName.Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                SL.EndTime = DateTime.Now;
                SF.logandshowInfo("上傳檔案結束@" + SL.EndTime.ToString(Configer.SystemDateTimeFormat), log_Info);
                SF.logandshowInfo("上傳檔案失敗，錯誤訊息[檔案格式錯誤]", log_Info);
                SL.TotalCount = 1;
                SL.SuccessCount = 0;
                SL.FailCount = 1;
                SL.Result = false;
                SL.Msg = "上傳檔案失敗，錯誤訊息[檔案格式錯誤]";
                SF.log2DB(SL, MailServer, MailServerPort, MailSender, MailReceiver);

                jo.Add("Result", false);
                jo.Add("Msg", "錯誤訊息[請上傳 .xls 或 .xlsx 格式的檔案]");
                result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }

            try
            {
                var uploadResult = this.FileUploadHandler(file);
                SL.EndTime = DateTime.Now;
                SF.logandshowInfo("上傳檔案結束@" + SL.EndTime.ToString(Configer.SystemDateTimeFormat), log_Info);
                SF.logandshowInfo("上傳檔案成功，檔案名稱[" + uploadResult.ToString() + "]", log_Info);
                SL.TotalCount = 1;
                SL.SuccessCount = 1;
                SL.FailCount = 0;
                SL.Result = true;
                SL.Msg = "上傳檔案成功，檔案名稱[" + uploadResult.ToString() + "]";
                SF.log2DB(SL, MailServer, MailServerPort, MailSender, MailReceiver);

                //解析Excel
                string fileName =Server.MapPath(Configer.UploadPath + uploadResult.ToString());
                result =AnalyticsCIData(fileName, ImportType);

                List<string> Results = StringProcessor.SplitString2Array(result, Configer.SplitSymbol.ToCharArray());

                jo.Add("Result", Convert.ToBoolean(Results[0]));
                jo.Add("Msg", !string.IsNullOrWhiteSpace(Results[1]) ? Results[1] : "");

                result = JsonConvert.SerializeObject(jo);
            }
            catch (Exception ex)
            {
                SL.EndTime = DateTime.Now;
                SF.logandshowInfo("上傳檔案結束@" + SL.EndTime.ToString(Configer.SystemDateTimeFormat), log_Info);
                SF.logandshowInfo("上傳檔案失敗，錯誤訊息[" + ex.ToString() + "]", log_Info);
                SL.TotalCount = 1;
                SL.SuccessCount = 0;
                SL.FailCount = 1;
                SL.Result = false;
                SL.Msg = "上傳檔案失敗，錯誤訊息[" + ex.ToString() + "]";
                SF.log2DB(SL, MailServer, MailServerPort, MailSender, MailReceiver);

                jo.Add("Result", false);
                jo.Add("Msg", "錯誤訊息[" + ex.ToString() + "]");
                result = JsonConvert.SerializeObject(jo);
            }
            return Content(result, "application/json");
        }

        /// <summary>
        /// Files the upload handler.
        /// </summary>
        /// <param name="file">The file.</param>
        /// <returns></returns>
        /// <exception cref="System.ArgumentNullException">file;上傳失敗：沒有檔案！</exception>
        /// <exception cref="System.InvalidOperationException">上傳失敗：檔案沒有內容！</exception>
        private string FileUploadHandler(HttpPostedFileBase file)
        {
            //初始化系統參數
            Configer.Init();

            string result;

            if (file == null)
            {
                throw new ArgumentNullException("file", "上傳失敗：沒有檔案！");
            }
            if (file.ContentLength <= 0)
            {
                throw new InvalidOperationException("上傳失敗：檔案沒有內容！");
            }

            try
            {
                string virtualBaseFilePath = Url.Content(Configer.UploadPath);
                string filePath = HttpContext.Server.MapPath(virtualBaseFilePath);

                if (!Directory.Exists(filePath))
                {
                    Directory.CreateDirectory(filePath);
                }

                string newFileName = string.Concat(
                    DateTime.Now.ToString("yyyyMMddHHmmssfff"),
                    Path.GetExtension(file.FileName).ToLower());

                string fullFilePath = Path.Combine(Server.MapPath(Configer.UploadPath), newFileName);
                file.SaveAs(fullFilePath);

                result = newFileName;
            }
            catch (Exception ex)
            {
                result = ex.ToString();
            }
            return result;
        }

        /// <summary>
        /// 解析Excel資料並匯入資料庫
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="ImportType"></param>
        /// <returns></returns>
        private string AnalyticsCIData(string fileName, string ImportType)
        {
            string nowUser = Session["UserID"].ToString();
            int nowRole = Convert.ToInt32(Session["UserRole"]);
            //int nowFunction = 15;

            //Log記錄用
            SystemLogs SL = new SystemLogs();
            SL.Account = nowUser;
            SL.Controller = "ImportCIController";
            SL.Action = "AnalyticsCIData";
            SL.StartTime = DateTime.Now;

            string MailServer = Configer.MailServer;
            int MailServerPort = Configer.MailServerPort;
            string MailSender = Configer.MailSender;
            List<string> MailReceiver = Configer.MailReceiver;

            string Result = string.Empty;

            SF.logandshowInfo("解析Excel檔案開始@" + SL.StartTime.ToString(Configer.SystemDateTimeFormat), log_Info);

            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {
                Result = "解析Excel檔案失敗，錯誤訊息[找不到指定檔案:" + fileName + "]";
                SL.EndTime = DateTime.Now;
                SF.logandshowInfo("解析Excel檔案結束@" + SL.EndTime.ToString(Configer.SystemDateTimeFormat), log_Info);
                SF.logandshowInfo("解析Excel檔案失敗，錯誤訊息[找不到指定檔案:" + fileName + "]", log_Info);
                SL.TotalCount = 1;
                SL.SuccessCount = 0;
                SL.FailCount = 1;
                SL.Result = false;
                SL.Msg = "解析Excel檔案失敗，錯誤訊息[找不到指定檔案:" + fileName + "]";
                SF.log2DB(SL, MailServer, MailServerPort, MailSender, MailReceiver);

                return Result;
            }
            else
            {
                string ImportAttributesResult = string.Empty;
                List<string> TmpImportAttributesResultList;
                string ImportProfilesResult = string.Empty;
                List<string> TmpImportProfilesResult;

CMDB/Views/ImportCI/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>批次匯入</h2>

<div class="well">
    <button class="btn btn-primary" data-toggle="modal" data-target="#UploadModal">
        匯入組態
    </button>
</div>

@Html.Partial("_UploadFile")

@section ImporrtCIScript
{
    <script>
        $(function () {
            $("#UploadForm").ajaxForm({
                iframe: true,
                dataType: "json",
                success: function (result) {
                    $("#UploadForm").resetForm();
                    if (!result.Result) {
                        $('#UploadModal').modal('hide');
                        bootbox.alert(result.Msg);
                    }
                    else {
                        $('#UploadModal').modal('hide');
                        bootbox.alert(result.Msg);
                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    $('#UploadModal').modal('hide');
                    bootbox.alert(result.Msg);
                }
            });
        });
    </script>
}

CMDB/Views/ImportCI/_UploadFile.cshtml
<!-- UploadModal -->
<div class="modal fade" id="UploadModal" tabindex="-1" role="dialog" aria-labelledby="UploadModalLabel" aria-hidden="true">
    <form id="UploadForm" action="@Url.Action("Upload", "ImportCI")" method="post"  enctype="multipart/form-data">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="UploadModalLabel">上傳並匯入資料</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <select class="form-control" name="ImportType">
                            <option value="Init" selected>初始化(只含屬性跟範本)</option>
                            <option value="All">全部</option>
                            <option value="Attribute">屬性</option>
                            <option value="Profile">範本</option>
                            <option value="Object">物件</option>
                        </select>
                    </div>
                    <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                        <div class="form-control" data-trigger="fileinput">
                            <i class="glyphicon glyphicon-file fileinput-exists"></i>
                            <span class="fileinput-filename"></span>
                        </div>
                        <span class="input-group-addon btn btn-default btn-file">
                            <span class="fileinput-new">選擇檔案</span>
                            <span class="fileinput-exists">更換檔案</span>
                            <input type="file" name="file" id="file" />
                        </span>
                        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">移除檔案</a>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" id="ButtonCancel" class="btn btn-default" data-dismiss="modal" value="取消">
                    <input type="submit" id="ButtonSubmit" name="ButtonSubmit" class="btn btn-primary" value="上傳檔案">
                </div>
            </div>
        </div>
    </form>
</div>